# Generated by Django 3.2.16 on 2023-08-18 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('informe', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('arch', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=5000)),
                ('detectado', models.FileField(upload_to='')),
                ('numero_linea', models.IntegerField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.analisis')),
                ('archivo_origen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analisis.archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=5000)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analisis.aplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('fecha_creacion', models.DateTimeField()),
                ('ultima_modificacion', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='archivo',
            name='carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.carpeta'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='aplicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analisis.aplicacion'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analisis.carpeta'),
        ),
    ]
